# Generated by Django 4.2.13 on 2025-08-28 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0040_alter_test_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestresult',
            name='test_case_version',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_case_version',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
