# Generated by Django 4.2.13 on 2026-03-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_environment_and_more'),
        ('tests_representation', '0041_alter_historicaltestresult_test_case_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestresult',
            name='environment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.environment'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Active'), (3, 'Completed'), (4, 'Archived')], default=1),
        ),
        migrations.AddField(
            model_name='testresult',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.environment'),
        ),
    ]
