# Generated by Django 4.2.13 on 2025-11-25 13:29
from copy import deepcopy

from django.db import migrations


def copy_history(step_history, case_history):
    new_history = deepcopy(step_history)
    new_history.pk = None
    new_history.test_case_history_id = case_history.pk
    new_history.history_date = case_history.history_date
    return new_history


def create_historical_test_case_steps(apps, schema_editor):
    test_case_history_model = apps.get_model('tests_description', 'HistoricalTestCase')
    test_case_step_model = apps.get_model('tests_description', 'TestCaseStep')
    test_case_step_history_model = apps.get_model('tests_description', 'HistoricalTestCaseStep')
    history_to_create = []
    for test_case in test_case_history_model.objects.filter(is_deleted=False, is_steps=True):
        steps_histories = (
            test_case_step_history_model
            .objects
            .filter(test_case_id=test_case.id)
        )
        version_steps_histories = steps_histories.filter(test_case_history_id=test_case.history_id)
        if version_steps_histories.exists():
            continue
        last_step_histories = (
            steps_histories
            .order_by('id', '-history_date')
            .distinct('id')
        )
        for last_step_history in last_step_histories:
            if test_case_step_model.objects.filter(id=last_step_history.id).exists():
                history_to_create.append(
                    copy_history(last_step_history, test_case)
                )

    test_case_step_history_model.objects.bulk_create(history_to_create, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0024_auto_20250528_1607'),
    ]

    operations = [
        migrations.RunPython(create_historical_test_case_steps, reverse_code=migrations.RunPython.noop),
    ]
