# Generated by Django 4.2.13 on 2025-08-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0028_added_indexes_for_historical_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_url', models.URLField()),
                ('is_new_tab', models.BooleanField(default=False)),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.project')),
            ],
            options={
                'verbose_name': 'Project integration',
                'verbose_name_plural': 'Project integrations',
            },
        ),
        migrations.AddConstraint(
            model_name='projectintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='unique_project_name_value_on_project_integration_for_soft_delete'),
        ),
    ]
