# Generated by Django 4.2.13 on 2025-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_projectintegration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
